import { defineConfig } from 'oxlint';

const MAX_COMPLEXITY = 10;
const MAX_DEPTH = 5;
const MAX_STATEMENTS = 15;
const MAX_NESTED_CALLBACKS = 3;

export default function oxlintConfig() {
    return defineConfig({
        categories: {
            correctness: 'error',
            pedantic: 'off',
            style: 'warn',
            suspicious: 'warn'
        },
        options: {
            maxWarnings: 0,
            typeAware: true,
            typeCheck: true
        },
        plugins: ['eslint', 'oxc', 'typescript', 'react'],
        rules: {
            'array-callback-return': 'error',
            'capitalized-comments': 'warn',
            'class-methods-use-this': 'warn',
            complexity: ['warn', MAX_COMPLEXITY],
            'consistent-return': 'warn',
            curly: ['warn', 'multi-or-nest'],
            'default-case': 'warn',
            'default-case-last': 'error',
            'dot-notation': 'warn',
            eqeqeq: 'warn',
            'func-names': 'error',
            'func-style': 'off',
            'id-length': 'off',
            'max-classes-per-file': ['warn', 1],
            'max-depth': ['warn', MAX_DEPTH],
            'max-nested-callbacks': ['warn', MAX_NESTED_CALLBACKS],
            'max-statements': ['warn', MAX_STATEMENTS],
            'no-alert': 'error',
            'no-array-constructor': 'warn',
            'no-await-in-loop': 'warn',
            'no-caller': 'error',
            'no-constructor-return': 'error',
            'no-duplicate-imports': 'error',
            'no-empty-function': 'warn',
            'no-eq-null': 'warn',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'warn',
            'no-implied-eval': 'warn',
            'no-inner-declarations': 'warn',
            'no-iterator': 'warn',
            'no-lone-blocks': 'warn',
            'no-loop-func': 'warn',
            'no-magic-numbers': ['warn', { enforceConst: true, ignore: [-1, 0, 1], ignoreArrayIndexes: true, ignoreClassFieldInitialValues: true }],
            'no-multi-assign': 'warn',
            'no-multi-str': 'warn',
            'no-negated-condition': 'warn',
            'no-nested-ternary': 'warn',
            'no-new': 'warn',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-object-constructor': 'error',
            'no-param-reassign': 'error',
            'no-promise-executor-return': 'error',
            'no-proto': 'error',
            'no-restricted-exports': 'warn',
            'no-restricted-globals': 'warn',
            'no-restricted-imports': 'warn',
            'no-restricted-properties': 'warn',
            'no-return-assign': 'error',
            'no-script-url': 'error',
            'no-self-assign': 'error',
            'no-sequences': 'warn',
            'no-shadow': 'warn',
            'no-template-curly-in-string': 'error',
            'no-ternary': 'off',
            'no-throw-literal': 'warn',
            'no-underscore-dangle': 'warn',
            'no-unmodified-loop-condition': 'error',
            'no-unneeded-ternary': 'warn',
            'no-unreachable-loop': 'error',
            'no-unused-expressions': 'warn',
            'no-use-before-define': 'warn',
            'no-useless-assignment': 'warn',
            'no-useless-call': 'warn',
            'no-useless-computed-key': 'warn',
            'no-useless-concat': 'warn',
            'no-useless-constructor': 'warn',
            'no-useless-rename': 'warn',
            'no-useless-return': 'warn',
            'no-var': 'error',
            'no-void': 'warn',
            'no-warning-comments': 'warn',
            'object-shorthand': 'warn',
            'one-var': 'off',
            'prefer-arrow-callback': 'warn',
            'prefer-const': 'warn',
            'prefer-destructuring': 'warn',
            'prefer-named-capture-group': 'warn',
            'prefer-numeric-literals': 'warn',
            'prefer-object-spread': 'warn',
            'prefer-promise-reject-errors': 'error',
            'prefer-regex-literals': 'warn',
            'prefer-rest-params': 'warn',
            'prefer-spread': 'warn',
            'react/jsx-max-depth': ['warn', { max: 5 }],
            'react/jsx-props-no-spreading': 'off',
            'react/react-in-jsx-scope': 'off',
            'require-await': 'warn',
            'require-yield': 'warn',
            'sort-imports': 'off',
            'sort-keys': ['warn', 'asc', { allowLineSeparatedGroups: true, natural: true }],
            'sort-vars': 'warn',
            'symbol-description': 'warn',
            'vars-on-top': 'warn',
            yoda: 'error'
        }
    });
}
